// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiidQrF_9v9G-aNs3KzeprGJjkH69aY2o',
    appId: '1:935784685786:web:29b39addc9548df17c05e3',
    messagingSenderId: '935784685786',
    projectId: 'privadocsapp',
    authDomain: 'privadocsapp.firebaseapp.com',
    storageBucket: 'privadocsapp.firebasestorage.app',
    measurementId: 'G-1DX0Q47W53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ-oOZbQGrJS0yOP9psaTqb2cUOcPa2kw',
    appId: '1:935784685786:android:f1d482e19e7125cb7c05e3',
    messagingSenderId: '935784685786',
    projectId: 'privadocsapp',
    storageBucket: 'privadocsapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTl11qryTro1i6KhsR82RrGYGWh9f8Hvw',
    appId: '1:935784685786:ios:3347e5f8bef184ae7c05e3',
    messagingSenderId: '935784685786',
    projectId: 'privadocsapp',
    storageBucket: 'privadocsapp.firebasestorage.app',
    iosBundleId: 'com.example.proyectoPrivadocs',
  );
}
